import fs from 'fs';

let content = fs.readFileSync('services/itemRenderer.ts', 'utf8');

const newCases = `
          case 'ARMOR':
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.moveTo(-10, -12);
              ctx.lineTo(10, -12);
              ctx.lineTo(14, -6);
              ctx.lineTo(10, 14);
              ctx.lineTo(0, 18);
              ctx.lineTo(-10, 14);
              ctx.lineTo(-14, -6);
              ctx.closePath();
              ctx.fill();
              ctx.strokeStyle = '#fff';
              ctx.lineWidth = 1;
              ctx.stroke();
              break;
          case 'BOOTS':
              ctx.fillStyle = color;
              ctx.fillRect(-10, -5, 8, 15);
              ctx.fillRect(2, -5, 8, 15);
              ctx.fillRect(-12, 10, 10, 5);
              ctx.fillRect(0, 10, 10, 5);
              ctx.strokeStyle = '#fff';
              ctx.strokeRect(-10, -5, 8, 15);
              ctx.strokeRect(2, -5, 8, 15);
              break;
          case 'RING':
              ctx.strokeStyle = '#fbbf24';
              ctx.lineWidth = 4;
              ctx.beginPath();
              ctx.arc(0, 0, 8, 0, Math.PI * 2);
              ctx.stroke();
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.arc(0, -8, 4, 0, Math.PI * 2);
              ctx.fill();
              break;
          case 'NECKLACE':
              ctx.strokeStyle = '#fbbf24';
              ctx.lineWidth = 2;
              ctx.beginPath();
              ctx.arc(0, -5, 10, 0, Math.PI);
              ctx.stroke();
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.moveTo(0, 12);
              ctx.lineTo(-5, 5);
              ctx.lineTo(5, 5);
              ctx.closePath();
              ctx.fill();
              break;
          case 'HELMET':
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.arc(0, 0, 12, Math.PI, 0);
              ctx.lineTo(12, 12);
              ctx.lineTo(-12, 12);
              ctx.closePath();
              ctx.fill();
              ctx.fillStyle = '#000';
              ctx.fillRect(-4, 0, 8, 4);
              break;
          case 'FOOD':
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.arc(0, 0, 10, 0, Math.PI * 2);
              ctx.fill();
              ctx.fillStyle = '#22c55e';
              ctx.fillRect(-2, -14, 4, 6);
              break;
          case 'POTION':
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.arc(0, 8, 10, 0, Math.PI * 2);
              ctx.fill();
              ctx.fillStyle = 'rgba(255,255,255,0.5)';
              ctx.fillRect(-4, -8, 8, 10);
              ctx.fillStyle = '#78350f';
              ctx.fillRect(-5, -12, 10, 4);
              break;
          case 'GEM':
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.moveTo(0, -12);
              ctx.lineTo(10, 0);
              ctx.lineTo(0, 12);
              ctx.lineTo(-10, 0);
              ctx.closePath();
              ctx.fill();
              ctx.strokeStyle = '#fff';
              ctx.lineWidth = 1;
              ctx.stroke();
              break;
          case 'BAR':
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.moveTo(-12, -6);
              ctx.lineTo(8, -6);
              ctx.lineTo(12, 6);
              ctx.lineTo(-8, 6);
              ctx.closePath();
              ctx.fill();
              ctx.strokeStyle = '#fff';
              ctx.lineWidth = 1;
              ctx.stroke();
              break;
          case 'SWORD':
              ctx.strokeStyle = '#94a3b8';
              ctx.lineWidth = 4;
              ctx.beginPath();
              ctx.moveTo(-12, 12);
              ctx.lineTo(12, -12);
              ctx.stroke();
              ctx.strokeStyle = color;
              ctx.lineWidth = 2;
              ctx.beginPath();
              ctx.moveTo(-6, 6);
              ctx.lineTo(14, -14);
              ctx.stroke();
              ctx.strokeStyle = '#fbbf24';
              ctx.lineWidth = 3;
              ctx.beginPath();
              ctx.moveTo(-10, 4);
              ctx.lineTo(-4, 10);
              ctx.stroke();
              break;
          case 'DAGGER':
              ctx.strokeStyle = '#94a3b8';
              ctx.lineWidth = 3;
              ctx.beginPath();
              ctx.moveTo(-8, 8);
              ctx.lineTo(8, -8);
              ctx.stroke();
              ctx.strokeStyle = color;
              ctx.lineWidth = 1.5;
              ctx.beginPath();
              ctx.moveTo(-4, 4);
              ctx.lineTo(10, -10);
              ctx.stroke();
              ctx.strokeStyle = '#fbbf24';
              ctx.lineWidth = 2;
              ctx.beginPath();
              ctx.moveTo(-6, 2);
              ctx.lineTo(-2, 6);
              ctx.stroke();
              break;
          case 'AXE':
              ctx.strokeStyle = '#78350f';
              ctx.lineWidth = 3;
              ctx.beginPath();
              ctx.moveTo(-10, 10);
              ctx.lineTo(10, -10);
              ctx.stroke();
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.arc(8, -8, 8, -Math.PI/4, Math.PI*3/4);
              ctx.fill();
              break;
          case 'MACE':
              ctx.strokeStyle = '#78350f';
              ctx.lineWidth = 3;
              ctx.beginPath();
              ctx.moveTo(-10, 10);
              ctx.lineTo(6, -6);
              ctx.stroke();
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.arc(8, -8, 6, 0, Math.PI * 2);
              ctx.fill();
              ctx.fillStyle = '#fff';
              ctx.fillRect(6, -16, 4, 4);
              ctx.fillRect(14, -8, 4, 4);
              ctx.fillRect(0, -8, 4, 4);
              ctx.fillRect(8, 0, 4, 4);
              break;
          case 'SPEAR':
              ctx.strokeStyle = '#78350f';
              ctx.lineWidth = 2;
              ctx.beginPath();
              ctx.moveTo(-14, 14);
              ctx.lineTo(10, -10);
              ctx.stroke();
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.moveTo(8, -8);
              ctx.lineTo(16, -16);
              ctx.lineTo(12, -4);
              ctx.closePath();
              ctx.fill();
              break;
          case 'STAFF':
              ctx.strokeStyle = '#78350f';
              ctx.lineWidth = 3;
              ctx.beginPath();
              ctx.moveTo(-12, 12);
              ctx.lineTo(8, -8);
              ctx.stroke();
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.arc(10, -10, 6, 0, Math.PI * 2);
              ctx.fill();
              break;
          case 'BOW':
              ctx.strokeStyle = '#78350f';
              ctx.lineWidth = 3;
              ctx.beginPath();
              ctx.arc(-4, -4, 14, -Math.PI/4, Math.PI*3/4);
              ctx.stroke();
              ctx.strokeStyle = '#fff';
              ctx.lineWidth = 1;
              ctx.beginPath();
              ctx.moveTo(6, -14);
              ctx.lineTo(-14, 6);
              ctx.stroke();
              break;
          case 'GUN':
              ctx.fillStyle = '#475569';
              ctx.fillRect(-8, 0, 6, 12);
              ctx.fillStyle = color;
              ctx.fillRect(-10, -6, 20, 8);
              ctx.fillStyle = '#0ea5e9';
              ctx.fillRect(6, -4, 4, 4);
              break;
          case 'FIST':
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.arc(0, 0, 10, 0, Math.PI * 2);
              ctx.fill();
              ctx.fillStyle = '#fff';
              ctx.fillRect(-8, -12, 4, 6);
              ctx.fillRect(-2, -14, 4, 6);
              ctx.fillRect(4, -12, 4, 6);
              break;
          case 'THROWING':
              ctx.fillStyle = color;
              ctx.beginPath();
              ctx.moveTo(0, -14);
              ctx.lineTo(4, 0);
              ctx.lineTo(0, 14);
              ctx.lineTo(-4, 0);
              ctx.closePath();
              ctx.fill();
              break;
          case 'BOOK':
              ctx.fillStyle = '#78350f';
              ctx.fillRect(-10, -12, 20, 24);
              ctx.fillStyle = color;
              ctx.fillRect(-8, -10, 16, 20);
              ctx.strokeStyle = '#fbbf24';
              ctx.lineWidth = 2;
              ctx.strokeRect(-6, -8, 12, 16);
              break;
`;

content = content.replace('              break;\n      }\n  }', '              break;' + newCases + '\n      }\n  }');

fs.writeFileSync('services/itemRenderer.ts', content);
